# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='about',
            field=models.CharField(default='Предприниматель', max_length=500),
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 10, 7, 56, 54, 40239, tzinfo=utc)),
        ),
    ]
