# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190410_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 10, 9, 16, 28, 796592, tzinfo=utc)),
        ),
    ]
