# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190410_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 10, 9, 28, 45, 785714, tzinfo=utc)),
        ),
    ]
