# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190410_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entr_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Administrator')),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='request',
            name='location',
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='birthday',
            field=models.DateField(default='2001-04-04'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='passport_number',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='passport_series',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='sex',
            field=models.BooleanField(choices=[(False, 'Женщина'), (True, 'Мужчина')], default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='unit_code',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 10, 14, 24, 40, 976241, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
