# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190410_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='birthday',
            field=models.DateField(default='2001-04-04'),
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 10, 14, 25, 58, 116140, tzinfo=utc)),
        ),
    ]
