# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190409_1854'),
        ('main', '0008_auto_20190410_2331'),
    ]

    operations = [
    ]
