# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20190411_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='birthday',
            field=models.DateField(default='2001-04-04'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='passport_number',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='passport_series',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='sex',
            field=models.BooleanField(choices=[(False, 'Женщина'), (True, 'Мужчина')], default=False),
        ),
        migrations.AddField(
            model_name='administrator',
            name='unit_code',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumer',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='telephone',
            field=models.CharField(default='Ни скажу!', max_length=100),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='wishes',
            field=models.CharField(default='Все не почём!', max_length=100),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='sex',
            field=models.BooleanField(choices=[(False, 'Женщина'), (True, 'Мужчина')], default=False),
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 10, 15, 15, 14, 761092, tzinfo=utc)),
        ),
    ]
