# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190411_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entr_request',
            name='administrator',
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 10, 15, 22, 11, 207608, tzinfo=utc)),
        ),
    ]
