# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190411_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entr_request',
            name='consumer',
        ),
        migrations.AddField(
            model_name='entr_request',
            name='administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Administrator'),
        ),
        migrations.AddField(
            model_name='entr_request',
            name='entrepreneur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Entr_Request'),
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 10, 15, 26, 54, 52459, tzinfo=utc)),
        ),
    ]
