# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190411_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entr_request',
            name='entrepreneur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Entrepreneur'),
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 10, 15, 33, 59, 560824, tzinfo=utc)),
        ),
    ]
