# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190411_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Entrepreneur')),
            ],
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 10, 17, 17, 50, 861445, tzinfo=utc)),
        ),
    ]
