# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-11 00:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190411_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='rate',
            new_name='rate_name',
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 11, 0, 50, 22, 540612, tzinfo=utc)),
        ),
    ]
