# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-11 00:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190411_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='rate_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 11, 0, 57, 16, 910452, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='resident',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer'),
        ),
        migrations.AddField(
            model_name='resident',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Entrepreneur'),
        ),
    ]
